### PR TITLE
Toggl Pipeline issue 

### PR DESCRIPTION
**Pull request by HazalCiplak**
https://github.com/elifesciences/data-hub-issues/issues/572

### CODE REVIEW

**Comment by HazalCiplak** [comment]
I have dissabled [attr-defined] mypy error code, because it was complaining about a third party library (`requests`).

**Comment by de-code** [comment]
> I have dissabled [attr-defined] mypy error code, because it was complaining about a third party library (`requests`).

Maybe in that case just ignoring the line via `# type: ignore` makes sense? (then we wouldn't ignore the linting for that for the whole project)

**Comment by HazalCiplak** [comment]
> > I have dissabled [attr-defined] mypy error code, because it was complaining about a third party library (`requests`).
> 
> Maybe in that case just ignoring the line via `# type: ignore` makes sense? (then we wouldn't ignore the linting for that for the whole project)

I have added like that but there was 4 different  places for same library, I thought it is not ignoring the linting just mypy as added in mypy.ini file. If it effects pylint, I can update but I am not sure how it does

**Comment by de-code** [comment]
> > > I have dissabled [attr-defined] mypy error code, because it was complaining about a third party library (`requests`).
> > 
> > 
> > Maybe in that case just ignoring the line via `# type: ignore` makes sense? (then we wouldn't ignore the linting for that for the whole project)
> 
> I have added like that but there was 4 different places for same library, I thought it is not ignoring the linting just mypy as added in mypy.ini file. If it effects pylint, I can update but I am not sure how it does

Maybe we can chat about. It wouldn't affect pylint. But mypy linting for other cases. `4` doesn't seem that much. But I don't completely understand where and what is causing it.

**Pull request merged**
