### PR TITLE
Web API: retrieve data ranges in batches

### PR DESCRIPTION
**Pull request by de-code**
part of https://github.com/elifesciences/data-hub-issues/issues/553

### CODE REVIEW

**Comment by de-code** [comment]
For other APIs we would request complete days, e.g. until yesterday. That is currently not implemented. But maybe that can be a future PR. This may be good enough for the purpose?
(For the CrossRef Event Data I think it is okay if there are the odd entries that are missing due to exact timestamps)

**Comment by de-code** [comment]
Getting this error:

```text
[2022-12-28, 09:30:24 UTC] {generic_web_api_data_etl.py:209} INFO - updating state to: datetime.datetime(2018, 1, 6, 23, 58, 58, tzinfo=<StaticTzInfo 'Z'>)
[2022-12-28, 09:30:25 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/web_api_data_import_pipeline.py", line 40, in web_api_data_etl
    generic_web_api_data_etl(
  File "/opt/airflow/data_pipeline/generic_web_api/generic_web_api_data_etl.py", line 243, in generic_web_api_data_etl
    if not next_from_timestamp or next_from_timestamp >= end_timestamp:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by de-code** [comment]
used the following config:

```json
{
   "dataPipelineId": "crossref_event_data_web_api_10",
   "gcpProjectName": "elife-data-pipeline",
   "importedTimestampFieldName": "imported_timestamp",
   "dataset": "de_dev",
   "table": "crossref_event_data_web_api",
   "stateFile": {
      "bucketName": "ci-elife-data-pipeline",
      "objectName": "by-env/de_dev/airflow-config/generic-web-api/de_dev-crossref-event-data-state-10.1101.json"
   },
   "dataUrl": {
      "urlExcludingConfigurableParameters": "https://api.eventdata.crossref.org/v1/events?rows=100&mailto=h.ciplak@elifesciences.org&obj-id.prefix=10.1101",
      "configurableParameters": {
         "nextPageCursorParameterName": "cursor",
         "fromDateParameterName": "from-collected-date",
         "toDateParameterName": "until-collected-date",
         "daysDiffFromStartTillEnd": 1,
         "defaultStartDate": "2018-01-01",
         "dateFormat": "%Y-%m-%d"
      }
   },
   "response": {
      "nextPageCursorKeyFromResponseRoot": [
         "message",
         "next-cursor"
      ],
      "itemsKeyFromResponseRoot": [
         "message",
         "events"
      ],
      "totalItemsCountKeyFromResponseRoot": [
         "message",
         "total-results"
      ],
      "recordTimestamp": {
         "itemTimestampKeyFromItemRoot": [
            "timestamp"
         ]
      }
   }
}
```

Now getting the following error for, unrelated to the change:

```text
[2022-12-28, 10:30:16 UTC] {generic_web_api_data_etl.py:99} INFO - Request URL: https://api.eventdata.crossref.org/v1/events?rows=100&mailto=h.ciplak@elifesciences.org&obj-id.prefix=10.1101&from-collected-date=2018-01-12&cursor=6ffa61ec-b8fe-48b0-81b4-ae551f94a5de&until-collected-date=2018-01-13
[2022-12-28, 10:30:16 UTC] {generic_web_api_data_etl.py:108} INFO - Headers: MappingConfig(printable_mapping={})
[2022-12-28, 10:30:17 UTC] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.eventdata.crossref.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2022-12-28, 10:30:18 UTC] {generate_schema.py:195} INFO - Processing line 1000
[2022-12-28, 10:30:19 UTC] {generate_schema.py:195} INFO - Processing line 2000
[2022-12-28, 10:30:19 UTC] {generate_schema.py:218} INFO - Processed 2946 lines
[2022-12-28, 10:30:33 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/web_api_data_import_pipeline.py", line 40, in web_api_data_etl
    generic_web_api_data_etl(
  File "/opt/airflow/data_pipeline/generic_web_api/generic_web_api_data_etl.py", line 241, in generic_web_api_data_etl
    process_web_api_data_etl_batch(
  File "/opt/airflow/data_pipeline/generic_web_api/generic_web_api_data_etl.py", line 208, in process_web_api_data_etl_batch
    load_written_data_to_bq(data_config, full_temp_file_location)
  File "/opt/airflow/data_pipeline/generic_web_api/generic_web_api_data_etl.py", line 268, in load_written_data_to_bq
    load_file_into_bq(
  File "/opt/airflow/data_pipeline/utils/data_store/bq_data_service.py", line 56, in load_file_into_bq
    job.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 708, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 2674; errors: 1. Please look into the errors[] collection for more details.
```

**Review by HazalCiplak — APPROVED** [review]

**Comment by de-code** [comment]
Also tested the pipeline with a config not using dates (this will run as part of the end to end tests as well):

```json
{
   "dataPipelineId": "test_people_api_1",
   "gcpProjectName": "elife-data-pipeline",
   "importedTimestampFieldName": "imported_timestamp",
   "dataset": "de_dev",
   "table": "test_people_api",
   "dataUrl": {
      "urlExcludingConfigurableParameters": "https://api.elifesciences.org/people?",
      "configurableParameters": {
         "pageSizeParameterName": "per-page",
         "defaultPageSize": 100,
         "pageParameterName": "page"
      }
   },
   "response": {
      "itemsKeyFromResponseRoot": [
         "items"
      ]
   }
}
```

**Pull request merged**
